name: Update README with Recent Activity

on:
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Update README with Recent GitHub Activity
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://@alibaqbani.hashnode.dev/rss.xml"
          max_post_count: 5
          readme_path: './README.md'
          comment_tag_name: "activity"
          commit_message: "chore: update readme with recent activity"
